services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=mydatabase'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    volumes:
      - postgres_dev:/var/lib/postgresql/data
    ports:
      - 5433:5432
volumes:
  postgres_dev: