name: Publish package to GitHub Packages
on:
  release:
    types: [created]
jobs:
  publish:
    runs-on: ubuntu-latest
    services:
        postgres:
          image: postgres
          env:
            POSTGRES_DB: mydatabase
            POSTGRES_PASSWORD: secret
            POSTGRES_USER: myuser
          volumes:
            - postgres_dev:/var/lib/postgresql/data
          ports:
            - 5433:5432
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Publish package
        run: ./mvnw --batch-mode deploy --settings ./.m2/settings.xml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          gh_packages_access_token: ${{ secrets.PACKAGES_ACCESS_TOKEN }}
